stages:
  download:
    cmd: uv run python src/download.py
    deps:
      - src/download.py
    outs:
      - data/raw/tweets.csv

  preprocess:
    cmd: uv run python src/preprocessing.py
    deps:
      - data/raw/tweets.csv
      - src/preprocessing.py
    outs:
      - data/processed/tweets_clean.csv

  train:
    cmd: uv run python src/models/train.py
    deps:
      - data/processed/tweets_clean.csv
      - src/models/train.py
    outs:
      - models/model.pkl
      - models/vectorizer.pkl
      - models/test_predictions.csv

  evaluate:
    cmd: uv run python src/models/evaluate.py
    deps:
      - models/test_predictions.csv
      - src/models/evaluate.py
    metrics:
      - models/metrics.json:
          cache: false
